services:
  - type: web
    name: websitescanner
    env: node
    plan: starter
    buildCommand: yarn install && npx playwright install --with-deps chromium
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
